/*This file was generated by NativeWind. Do not edit!*/
const {
  NativeWindStyleSheet: _NativeWindStyleSheet
} = require("nativewind");
_NativeWindStyleSheet.create({
  styles: {
    "*": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid",
      "borderTopColor": "#e5e7eb",
      "borderRightColor": "#e5e7eb",
      "borderBottomColor": "#e5e7eb",
      "borderLeftColor": "#e5e7eb"
    },
    "": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid",
      "borderTopColor": "#e5e7eb",
      "borderRightColor": "#e5e7eb",
      "borderBottomColor": "#e5e7eb",
      "borderLeftColor": "#e5e7eb"
    },
    "html": {
      "lineHeight": 1.5,
      "fontFamily": "ui-sans-serif"
    },
    ":host": {
      "lineHeight": 1.5,
      "fontFamily": "ui-sans-serif"
    },
    "body": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "hr": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "abbr:where([title])": {
      "textDecorationLine": "underline",
      "textDecorationColor": "black",
      "textDecorationStyle": "dotted"
    },
    "code": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "kbd": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "samp": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "pre": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "small": {
      "fontSize": "80%"
    },
    "sub": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "sup": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "button": {
      "backgroundColor": "transparent"
    },
    "input": {
      "opacity": 1,
      "color": "#9ca3af"
    },
    "optgroup": {
      "fontFamily": "inherit",
      "fontSize": "100%",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "select": {
      "textTransform": "none"
    },
    "textarea": {
      "opacity": 1,
      "color": "#9ca3af"
    },
    "[type='button']": {
      "backgroundColor": "transparent"
    },
    "[type='reset']": {
      "backgroundColor": "transparent"
    },
    "[type='submit']": {
      "backgroundColor": "transparent"
    },
    ":-moz-ui-invalid": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "black",
      "shadowOpacity": 1
    },
    "blockquote": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dl": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dd": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h1": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h2": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h3": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h4": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h5": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h6": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "figure": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "p": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "fieldset": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "legend": {
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ol": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ul": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "menu": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "dialog": {
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "img": {
      "maxWidth": "100%"
    },
    "video": {
      "maxWidth": "100%"
    },
    "[hidden]": {
      "display": "none"
    },
    "shadow@0": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@1": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@2": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "absolute": {
      "position": "absolute"
    },
    "relative": {
      "position": "relative"
    },
    "-top-4": {
      "top": -16
    },
    "flex": {
      "display": "flex"
    },
    "h-14": {
      "height": 56
    },
    "w-14": {
      "width": 56
    },
    "w-full": {
      "width": "100%"
    },
    "flex-grow": {
      "flexGrow": 1
    },
    "flex-row": {
      "flexDirection": "row"
    },
    "flex-col": {
      "flexDirection": "column"
    },
    "items-center": {
      "alignItems": "center"
    },
    "items-stretch": {
      "alignItems": "stretch"
    },
    "justify-center": {
      "justifyContent": "center"
    },
    "justify-between": {
      "justifyContent": "space-between"
    },
    "truncate": {
      "overflow": "hidden"
    },
    "rounded": {
      "borderTopLeftRadius": 4,
      "borderTopRightRadius": 4,
      "borderBottomRightRadius": 4,
      "borderBottomLeftRadius": 4
    },
    "border-2": {
      "borderTopWidth": 2,
      "borderRightWidth": 2,
      "borderBottomWidth": 2,
      "borderLeftWidth": 2
    },
    "border-b-2": {
      "borderBottomWidth": 2
    },
    "bg-blue-500": {
      "backgroundColor": "#3b82f6"
    },
    "bg-gray-200": {
      "backgroundColor": "#e5e7eb"
    },
    "bg-red-500": {
      "backgroundColor": "#ef4444"
    },
    "bg-slate-200": {
      "backgroundColor": "#e2e8f0"
    },
    "bg-white": {
      "backgroundColor": "#fff"
    },
    "px-4": {
      "paddingLeft": 16,
      "paddingRight": 16
    },
    "py-4": {
      "paddingTop": 16,
      "paddingBottom": 16
    },
    "text-center": {
      "textAlign": "center"
    },
    "font-bold": {
      "fontWeight": "700"
    },
    "capitalize": {
      "textTransform": "capitalize"
    },
    "text-blue-500": {
      "color": "#3b82f6"
    },
    "underline": {
      "textDecorationLine": "underline"
    },
    "color-blue-500": {
      "color": "#3b82f6"
    },
    "color-red-500": {
      "color": "#ef4444"
    },
    "gap-0": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-0.children@0": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1": {
      "marginLeft": -4,
      "marginTop": -4
    },
    "gap-1.children@0": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2": {
      "marginLeft": -8,
      "marginTop": -8
    },
    "gap-2.children@0": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4": {
      "marginLeft": -16,
      "marginTop": -16
    },
    "gap-4.children@0": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4": {
      "marginTop": -16
    },
    "gap-y-4.children@0": {
      "marginTop": 16
    },
    "text-2xl": {
      "fontSize": 24,
      "lineHeight": 32
    },
    "text-4xl": {
      "fontSize": 36,
      "lineHeight": 40
    },
    "text-xl": {
      "fontSize": 20,
      "lineHeight": 28
    },
    "text-xs": {
      "fontSize": 12,
      "lineHeight": 16
    },
    "leading-6": {
      "lineHeight": 24
    },
    "shadow@3": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@4": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@5": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "gap-0.children@1": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1.children@1": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2.children@1": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4.children@1": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4.children@1": {
      "marginTop": 16
    },
    "shadow@6": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@7": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@8": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "gap-0.children@2": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1.children@2": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2.children@2": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4.children@2": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4.children@2": {
      "marginTop": 16
    },
    "shadow@9": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@10": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@11": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "bg-green-500": {
      "backgroundColor": "#22c55e"
    },
    "gap-0.children@3": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1.children@3": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2.children@3": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4.children@3": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4.children@3": {
      "marginTop": 16
    },
    "shadow@12": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@13": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@14": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "gap-0.children@4": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1.children@4": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2.children@4": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4.children@4": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4.children@4": {
      "marginTop": 16
    },
    "shadow@15": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@16": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@17": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "gap-0.children@5": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1.children@5": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2.children@5": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4.children@5": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4.children@5": {
      "marginTop": 16
    },
    "shadow@18": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@19": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@20": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "bg-slate-100": {
      "backgroundColor": "#f1f5f9"
    },
    "gap-0.children@6": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1.children@6": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2.children@6": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4.children@6": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4.children@6": {
      "marginTop": 16
    },
    "shadow@21": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@22": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@23": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "gap-0.children@7": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1.children@7": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2.children@7": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4.children@7": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4.children@7": {
      "marginTop": 16
    },
    "shadow@24": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@25": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@26": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "gap-0.children@8": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1.children@8": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2.children@8": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4.children@8": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4.children@8": {
      "marginTop": 16
    },
    "shadow@27": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@28": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@29": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "gap-0.children@9": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1.children@9": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2.children@9": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4.children@9": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4.children@9": {
      "marginTop": 16
    },
    "shadow@30": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@31": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@32": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "gap-0.children@10": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1.children@10": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2.children@10": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4.children@10": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4.children@10": {
      "marginTop": 16
    },
    "shadow@33": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@34": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@35": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "gap-0.children@11": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1.children@11": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2.children@11": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4.children@11": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4.children@11": {
      "marginTop": 16
    },
    "shadow@36": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@37": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@38": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "gap-0.children@12": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1.children@12": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2.children@12": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4.children@12": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4.children@12": {
      "marginTop": 16
    },
    "shadow@39": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@40": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@41": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "gap-0.children@13": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1.children@13": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2.children@13": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4.children@13": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4.children@13": {
      "marginTop": 16
    },
    "shadow@42": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@43": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@44": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "gap-0.children@14": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1.children@14": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2.children@14": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4.children@14": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4.children@14": {
      "marginTop": 16
    },
    "shadow@45": {
      "elevation": 3,
      "shadowColor": "rgba(0, 0, 0, 0.1)"
    },
    "shadow@46": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "shadow@47": {
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 6,
      "shadowColor": "rgba(0, 0, 0, 0.1)",
      "shadowOpacity": 1
    },
    "gap-0.children@15": {
      "marginLeft": 0,
      "marginTop": 0
    },
    "gap-1.children@15": {
      "marginLeft": 4,
      "marginTop": 4
    },
    "gap-2.children@15": {
      "marginLeft": 8,
      "marginTop": 8
    },
    "gap-4.children@15": {
      "marginLeft": 16,
      "marginTop": 16
    },
    "gap-y-4.children@15": {
      "marginTop": 16
    }
  },
  atRules: {
    "shadow": [[["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]], [["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "gap-0.children": [[["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]]],
    "gap-1.children": [[["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]]],
    "gap-2.children": [[["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]]],
    "gap-4.children": [[["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]]],
    "gap-y-4.children": [[["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]], [["selector", "(> *)"]]]
  },
  childClasses: {
    "gap-0": ["gap-0.children", "gap-0.children", "gap-0.children", "gap-0.children", "gap-0.children", "gap-0.children", "gap-0.children", "gap-0.children", "gap-0.children", "gap-0.children", "gap-0.children", "gap-0.children", "gap-0.children", "gap-0.children", "gap-0.children", "gap-0.children"],
    "gap-1": ["gap-1.children", "gap-1.children", "gap-1.children", "gap-1.children", "gap-1.children", "gap-1.children", "gap-1.children", "gap-1.children", "gap-1.children", "gap-1.children", "gap-1.children", "gap-1.children", "gap-1.children", "gap-1.children", "gap-1.children", "gap-1.children"],
    "gap-2": ["gap-2.children", "gap-2.children", "gap-2.children", "gap-2.children", "gap-2.children", "gap-2.children", "gap-2.children", "gap-2.children", "gap-2.children", "gap-2.children", "gap-2.children", "gap-2.children", "gap-2.children", "gap-2.children", "gap-2.children", "gap-2.children"],
    "gap-4": ["gap-4.children", "gap-4.children", "gap-4.children", "gap-4.children", "gap-4.children", "gap-4.children", "gap-4.children", "gap-4.children", "gap-4.children", "gap-4.children", "gap-4.children", "gap-4.children", "gap-4.children", "gap-4.children", "gap-4.children", "gap-4.children"],
    "gap-y-4": ["gap-y-4.children", "gap-y-4.children", "gap-y-4.children", "gap-y-4.children", "gap-y-4.children", "gap-y-4.children", "gap-y-4.children", "gap-y-4.children", "gap-y-4.children", "gap-y-4.children", "gap-y-4.children", "gap-y-4.children", "gap-y-4.children", "gap-y-4.children", "gap-y-4.children", "gap-y-4.children"]
  }
});